/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ChainTraceHealth {
      
    export type SupplyChainEventStruct = {actor: AddressLike, role: string, timestamp: BigNumberish, location: string, authorized: boolean}

    export type SupplyChainEventStructOutput = [actor: string, role: string, timestamp: bigint, location: string, authorized: boolean] & {actor: string, role: string, timestamp: bigint, location: string, authorized: boolean }
  
    }

  export interface ChainTraceHealthInterface extends Interface {
    getFunction(nameOrSignature: "addApprovedPartner" | "addSupplyChainEvent" | "getAllBatchHashes" | "getApprovedPartners" | "getBatchCount" | "getBatchHistory" | "getBatchStatusByHash" | "getDivergencePoint" | "getDivergencePointByHash" | "isApprovedPartner" | "recallBatch" | "registerBatch" | "removeApprovedPartner" | "verifyBatch"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchRecalled" | "BatchRegistered" | "PartnerAdded" | "PartnerRemoved" | "SupplyChainEventAdded"): EventFragment;

    encodeFunctionData(functionFragment: 'addApprovedPartner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addSupplyChainEvent', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'getAllBatchHashes', values?: undefined): string;
encodeFunctionData(functionFragment: 'getApprovedPartners', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getBatchCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBatchHistory', values: [string]): string;
encodeFunctionData(functionFragment: 'getBatchStatusByHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getDivergencePoint', values: [string]): string;
encodeFunctionData(functionFragment: 'getDivergencePointByHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isApprovedPartner', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'recallBatch', values: [string, string]): string;
encodeFunctionData(functionFragment: 'registerBatch', values: [string, string, BigNumberish, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'removeApprovedPartner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyBatch', values: [string]): string;

    decodeFunctionResult(functionFragment: 'addApprovedPartner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addSupplyChainEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllBatchHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApprovedPartners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatchCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatchHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatchStatusByHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDivergencePoint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDivergencePointByHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedPartner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recallBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeApprovedPartner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyBatch', data: BytesLike): Result;
  }

  
    export namespace BatchRecalledEvent {
      export type InputTuple = [batchIdHash: BytesLike, reason: string, recalledBy: AddressLike];
      export type OutputTuple = [batchIdHash: string, reason: string, recalledBy: string];
      export interface OutputObject {batchIdHash: string, reason: string, recalledBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchRegisteredEvent {
      export type InputTuple = [batchIdHash: BytesLike, batchId: string, medicineName: string, manufacturer: AddressLike, expiryDate: BigNumberish];
      export type OutputTuple = [batchIdHash: string, batchId: string, medicineName: string, manufacturer: string, expiryDate: bigint];
      export interface OutputObject {batchIdHash: string, batchId: string, medicineName: string, manufacturer: string, expiryDate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PartnerAddedEvent {
      export type InputTuple = [manufacturer: AddressLike, partner: AddressLike];
      export type OutputTuple = [manufacturer: string, partner: string];
      export interface OutputObject {manufacturer: string, partner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PartnerRemovedEvent {
      export type InputTuple = [manufacturer: AddressLike, partner: AddressLike];
      export type OutputTuple = [manufacturer: string, partner: string];
      export interface OutputObject {manufacturer: string, partner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SupplyChainEventAddedEvent {
      export type InputTuple = [batchIdHash: BytesLike, actor: AddressLike, role: string, authorized: boolean, timestamp: BigNumberish];
      export type OutputTuple = [batchIdHash: string, actor: string, role: string, authorized: boolean, timestamp: bigint];
      export interface OutputObject {batchIdHash: string, actor: string, role: string, authorized: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ChainTraceHealth extends BaseContract {
    
    connect(runner?: ContractRunner | null): ChainTraceHealth;
    waitForDeployment(): Promise<this>;

    interface: ChainTraceHealthInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addApprovedPartner: TypedContractMethod<
      [partner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addSupplyChainEvent: TypedContractMethod<
      [batchId: string, role: string, location: string, ],
      [void],
      'nonpayable'
    >
    

    
    getAllBatchHashes: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getApprovedPartners: TypedContractMethod<
      [custodian: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getBatchCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getBatchHistory: TypedContractMethod<
      [batchId: string, ],
      [ChainTraceHealth.SupplyChainEventStructOutput[]],
      'view'
    >
    

    
    getBatchStatusByHash: TypedContractMethod<
      [batchIdHash: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getDivergencePoint: TypedContractMethod<
      [batchId: string, ],
      [[string, string] & {lastAuthorized: string, firstUnauthorized: string }],
      'view'
    >
    

    
    getDivergencePointByHash: TypedContractMethod<
      [batchIdHash: BytesLike, ],
      [[string, string] & {lastAuthorized: string, firstUnauthorized: string }],
      'view'
    >
    

    
    isApprovedPartner: TypedContractMethod<
      [custodian: AddressLike, partner: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    recallBatch: TypedContractMethod<
      [batchId: string, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    registerBatch: TypedContractMethod<
      [batchId: string, medicineName: string, manufacturingDate: BigNumberish, expiryDate: BigNumberish, quantity: BigNumberish, initialLocation: string, ],
      [void],
      'nonpayable'
    >
    

    
    removeApprovedPartner: TypedContractMethod<
      [partner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyBatch: TypedContractMethod<
      [batchId: string, ],
      [[boolean, string, string, bigint, bigint, bigint, string, bigint, string] & {exists: boolean, medicineName: string, bId: string, manufacturingDate: bigint, expiryDate: bigint, quantity: bigint, manufacturer: string, status: bigint, recallReason: string }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addApprovedPartner'): TypedContractMethod<
      [partner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addSupplyChainEvent'): TypedContractMethod<
      [batchId: string, role: string, location: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllBatchHashes'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getApprovedPartners'): TypedContractMethod<
      [custodian: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getBatchCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBatchHistory'): TypedContractMethod<
      [batchId: string, ],
      [ChainTraceHealth.SupplyChainEventStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getBatchStatusByHash'): TypedContractMethod<
      [batchIdHash: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDivergencePoint'): TypedContractMethod<
      [batchId: string, ],
      [[string, string] & {lastAuthorized: string, firstUnauthorized: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getDivergencePointByHash'): TypedContractMethod<
      [batchIdHash: BytesLike, ],
      [[string, string] & {lastAuthorized: string, firstUnauthorized: string }],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedPartner'): TypedContractMethod<
      [custodian: AddressLike, partner: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recallBatch'): TypedContractMethod<
      [batchId: string, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerBatch'): TypedContractMethod<
      [batchId: string, medicineName: string, manufacturingDate: BigNumberish, expiryDate: BigNumberish, quantity: BigNumberish, initialLocation: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeApprovedPartner'): TypedContractMethod<
      [partner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyBatch'): TypedContractMethod<
      [batchId: string, ],
      [[boolean, string, string, bigint, bigint, bigint, string, bigint, string] & {exists: boolean, medicineName: string, bId: string, manufacturingDate: bigint, expiryDate: bigint, quantity: bigint, manufacturer: string, status: bigint, recallReason: string }],
      'view'
    >;

    getEvent(key: 'BatchRecalled'): TypedContractEvent<BatchRecalledEvent.InputTuple, BatchRecalledEvent.OutputTuple, BatchRecalledEvent.OutputObject>;
getEvent(key: 'BatchRegistered'): TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
getEvent(key: 'PartnerAdded'): TypedContractEvent<PartnerAddedEvent.InputTuple, PartnerAddedEvent.OutputTuple, PartnerAddedEvent.OutputObject>;
getEvent(key: 'PartnerRemoved'): TypedContractEvent<PartnerRemovedEvent.InputTuple, PartnerRemovedEvent.OutputTuple, PartnerRemovedEvent.OutputObject>;
getEvent(key: 'SupplyChainEventAdded'): TypedContractEvent<SupplyChainEventAddedEvent.InputTuple, SupplyChainEventAddedEvent.OutputTuple, SupplyChainEventAddedEvent.OutputObject>;

    filters: {
      
      'BatchRecalled(bytes32,string,address)': TypedContractEvent<BatchRecalledEvent.InputTuple, BatchRecalledEvent.OutputTuple, BatchRecalledEvent.OutputObject>;
      BatchRecalled: TypedContractEvent<BatchRecalledEvent.InputTuple, BatchRecalledEvent.OutputTuple, BatchRecalledEvent.OutputObject>;
    

      'BatchRegistered(bytes32,string,string,address,uint256)': TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
      BatchRegistered: TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
    

      'PartnerAdded(address,address)': TypedContractEvent<PartnerAddedEvent.InputTuple, PartnerAddedEvent.OutputTuple, PartnerAddedEvent.OutputObject>;
      PartnerAdded: TypedContractEvent<PartnerAddedEvent.InputTuple, PartnerAddedEvent.OutputTuple, PartnerAddedEvent.OutputObject>;
    

      'PartnerRemoved(address,address)': TypedContractEvent<PartnerRemovedEvent.InputTuple, PartnerRemovedEvent.OutputTuple, PartnerRemovedEvent.OutputObject>;
      PartnerRemoved: TypedContractEvent<PartnerRemovedEvent.InputTuple, PartnerRemovedEvent.OutputTuple, PartnerRemovedEvent.OutputObject>;
    

      'SupplyChainEventAdded(bytes32,address,string,bool,uint256)': TypedContractEvent<SupplyChainEventAddedEvent.InputTuple, SupplyChainEventAddedEvent.OutputTuple, SupplyChainEventAddedEvent.OutputObject>;
      SupplyChainEventAdded: TypedContractEvent<SupplyChainEventAddedEvent.InputTuple, SupplyChainEventAddedEvent.OutputTuple, SupplyChainEventAddedEvent.OutputObject>;
    
    };
  }